[package]
name = "rename-seq"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
clap = { version = "3.2.17", features = ["derive"] }
color-eyre = "0.6.2"
itertools = "0.10.3"
snafu = "0.7.1"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
wax = "0.5.0"
